FORMAT: 1A
HOST: https://docs.xs2929.apiary.io

# OverwatchDB API

OverwatchDB API is a project  aiming to share Overwatch lovers both player performance statistics and in-game lore. 

The API is currently tracking Overwatch Heros, Maps, Roles, Events, Players and Organizations. 


## Hero Collection [/heroes]

### List All Heroes [GET]

+ Response 200 (application/json)

        {
            "num_results": 2,
            "objects": [
                    {
                            "id": 1,
                            "name": "Ana",
                            "description": "Ana’s versatile arsenal allows her to affect heroes all over the battlefield. Her Biotic Rifle rounds and Biotic Grenades heal allies and damage or impair enemies; her sidearm tranquilizes key targets, and Nano Boost gives one of her comrades a considerable increase in power.",
                            "health": 200,
                            "armour": 0,
                            "shield": 0,
                            "real_name": "Ana Amari",
                            "affiliation": "Overwatch",
                            "difficulty": 3,
                            "role": {
                                    "id": 4,
                                    "name": "support"
                            },
                            "sub_roles": [
                                    {
                                            "id": 2,
                                            "name": "healer"
                                    },
                                    {
                                            "id": 3,
                                            "name": "sniper"
                                    }
                            ],
                            "abilities": [
                                    {
                                            "id": 1,
                                            "name": "Biotic Rifle",
                                            "description": "Ana’s rifle shoots darts that can restore health to her allies or deal ongoing damage to her enemies. She can use the rifle’s scope to zoom in on targets and make highly accurate shots.",
                                            "is_ultimate": false
                                    },
                                    {
                                            "id": 2,
                                            "name": "Sleep Dart",
                                            "description": "Ana fires a dart from her sidearm, rendering an enemy unconscious (though any damage will rouse them).",
                                            "is_ultimate": false
                                    },
                                    {
                                            "id": 3,
                                            "name": "Biotic Grenade",
                                            "description": "Ana tosses a biotic bomb that deals damage to enemies and heals allies in a small area of effect. Affected allies briefly receive increased healing from all sources, while enemies caught in the blast cannot be healed for a few moments.",
                                            "is_ultimate": false
                                    },
                                    {
                                            "id": 4,
                                            "name": "Nano Boost",
                                            "description": "After Ana hits one of her allies with a combat boost, they temporarily move faster, deal more damage, and take less damage from enemies’ attacks.",
                                            "is_ultimate": true
                                    }
                            ],
                            "rewards": [
                                    {
                                            "id": 46,
                                            "name": "Action",
                                            "cost": {
                                                    "currency": "credit",
                                                    "value": 25
                                            },
                                            "type": {
                                                    "id": 1,
                                                    "name": "spray"
                                            },
                                            "quality": {
                                                    "name": "common"
                                            },
                                            "event": null
                                    }
                            ]
                    },
                    {
                            "id": 2,
                            "name": "Bastion",
                            "description": "Repair protocols and the ability to transform between stationary Assault, mobile Recon and devastating Tank configurations provide Bastion with a high probability of victory.",
                            "health": 200,
                            "armour": 100,
                            "shield": 0,
                            "real_name": "SST Laboratories Siege Automaton E54",
                            "affiliation": null,
                            "difficulty": 1,
                            "role": {
                                    "id": 2,
                                    "name": "defense"
                            },
                            "sub_roles": [],
                            "abilities": [
                                    {
                                            "id": 5,
                                            "name": "Configuration: Recon",
                                            "description": "In Recon mode, Bastion is fully mobile, outfitted with a submachine gun that fires steady bursts of bullets at medium range.",
                                            "is_ultimate": false
                                    },
                                    {
                                            "id": 6,
                                            "name": "Configuration: Sentry",
                                            "description": "In Sentry mode, Bastion is a stationary powerhouse equipped with a gatling gun capable of unleashing a hail of bullets. The gun's aim can be \"walked\" across multiple targets dealing devastating damage at short to medium range.",
                                            "is_ultimate": false
                                    },
                                    {
                                            "id": 7,
                                            "name": "Reconfigure",
                                            "description": "Bastion transforms between its two primary combat modes to adapt to changing battlefield conditions.",
                                            "is_ultimate": false
                                    },
                                    {
                                            "id": 8,
                                            "name": "Self-Repair",
                                            "description": "Bastion restores its health; it cannot move or fire weapons while the repair process is in effect.",
                                            "is_ultimate": false
                                    },
                                    {
                                            "id": 9,
                                            "name": "Configuration: Tank",
                                            "description": "In Tank mode, Bastion extends wheeled treads and a powerful long-range cannon. The cannon’s explosive shells demolish targets in a wide blast radius, but Bastion can only remain in this mode for a limited time.",
                                            "is_ultimate": true
                                    }
                            ],
                            "rewards": [
                                    {
                                            "id": 71,
                                            "name": "Action",
                                            "cost": {
                                                    "currency": "credit",
                                                    "value": 25
                                            },
                                            "type": {
                                                    "id": 1,
                                                    "name": "spray"
                                            },
                                            "quality": {
                                                    "name": "common"
                                            },
                                            "event": null
                                    }
                            ]
                    }
            ]
        }

### Find Hero [GET /heroes/{id}]

+ Parameters
    + id (optional, integer, `1`) ... Hero ID

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Ana",
            "description": "Ana’s versatile arsenal allows her to affect heroes all over the battlefield. Her Biotic Rifle rounds and Biotic Grenades heal allies and damage or impair enemies; her sidearm tranquilizes key targets, and Nano Boost gives one of her comrades a considerable increase in power.",
            "health": 200,
            "armour": 0,
            "shield": 0,
            "real_name": "Ana Amari",
            "age": 60,
            "affiliation": "Overwatch",
            "difficulty": 3,
            "role": {
                    "id": 4,
                    "name": "support"
            },
            "sub_roles": [
                    {
                            "id": 2,
                            "name": "healer"
                    },
                    {
                            "id": 3,
                            "name": "sniper"
                    }
            ],
            "abilities": [
                    {
                            "id": 1,
                            "name": "Biotic Rifle",
                            "description": "Ana’s rifle shoots darts that can restore health to her allies or deal ongoing damage to her enemies. She can use the rifle’s scope to zoom in on targets and make highly accurate shots.",
                            "is_ultimate": false
                    },
                    {
                            "id": 2,
                            "name": "Sleep Dart",
                            "description": "Ana fires a dart from her sidearm, rendering an enemy unconscious (though any damage will rouse them).",
                            "is_ultimate": false
                    },
                    {
                            "id": 3,
                            "name": "Biotic Grenade",
                            "description": "Ana tosses a biotic bomb that deals damage to enemies and heals allies in a small area of effect. Affected allies briefly receive increased healing from all sources, while enemies caught in the blast cannot be healed for a few moments.",
                            "is_ultimate": false
                    },
                    {
                            "id": 4,
                            "name": "Nano Boost",
                            "description": "After Ana hits one of her allies with a combat boost, they temporarily move faster, deal more damage, and take less damage from enemies’ attacks.",
                            "is_ultimate": true
                    }
            ],
            "rewards": [
                    {
                            "id": 46,
                            "name": "Action",
                            "cost": {
                                    "currency": "credit",
                                    "value": 25
                            },
                            "type": {
                                    "id": 1,
                                    "name": "spray"
                            },
                            "quality": {
                                    "name": "common"
                            },
                            "event": null
                    }
            ]
        }
    
## Players Collection [/players]

### Find Player [GET /players/{id}]

+ Parameters
    + id (optional, integer, `1`) ... Players ID

+ Response 200 (application/json)

        {
            "_request": {
                "api_ver": 3,
                "route": "/api/v3/u/Dad-12262/blob"
            },
            "kr": null,
            "eu": null,
            "us": {
                "stats": {},
                "heroes": {},
                "achievements": {}
            },
            "any": null
        }

## Reward Collection [/rewards]

### List All Rewards [GET /rewards/]

+ Response 200 (application/json)

        {
          "total": 2,
          "data": [
            {
              "id": 1,
              "name": "Logo",
              "cost": null,
              "type": {
                "id": 1,
                "name": "spray",
              },
              "quality": {
                "name": "common"
              }
            },
            {
              "id": 2,
              "name": "You Are Not Prepared!",
              "cost": null,
              "type": {
                "id": 1,
                "name": "spray",
              },
              "quality": {
                "name": "common"
              }
            }
          ]
        }   

### Find Reward [GET /rewards/{id}]

+ Parameters
    + id (optional, integer, `1`) ... Rewards ID

+ Response 200 (application/json)

        {  
           "id":50,
           "name":"Cracked",
           "cost":{  
              "currency":"credit",
              "value":25
           },
           "type":{
              "id":1,
              "name":"spray"
           },
           "hero":{  
              "id":1,
              "name":"Ana",
              "health":200,
              "armour":0,
              "shield":0,
              "real_name":"Ana Amari",
              "affiliation":"Overwatch",
              "difficulty":3,
              "description":"Ana’s versatile arsenal allows her to affect heroes all over the battlefield. Her Biotic Rifle rounds and Biotic Grenades heal allies and damage or impair enemies; her sidearm tranquilizes key targets, and Nano Boost gives one of her comrades a considerable increase in power."
           },
           "quality":{  
              "name":"common"
           },
           "event":null
        }

## Achievements Collection [/achievements]

### List All Achievements [GET /achievements/]

+ Response 200 (application/json)

        {
                "total": 2,
                "data": [
                        {
                                "id": 1,
                                "name": "Level 10",
                                "description": "Reach level 10.",
                                "hero": null,
                                "reward": {
                                        "id": 30,
                                        "name": "Forge Onward",
                                        "cost": null,
                                        "type": {
                                                "id": 1,
                                                "name": "spray"
                                        },
                                        "quality": {
                                                "name": "common"
                                        }
                                }
                        },
                        {
                                "id": 2,
                                "name": "Level 25",
                                "description": "Reach level 25.",
                                "hero": null,
                                "reward": {
                                        "id": 40,
                                        "name": "Rise",
                                        "cost": null,
                                        "type": {
                                                "id": 1,
                                                "name": "spray"
                                        },
                                        "quality": {
                                                "name": "common"
                                        }
                                }
                        }
                ]
        }


### Find Achievement [GET /achievements/{id}]

+ Parameters
    + id (optional, integer, `1`) ... Achievements ID

+ Response 200 (application/json)

        {  
           "id":1,
           "name":"Level 10",
           "description":"Reach level 10.",
           "hero":null,
           "reward":{  
              "id":30,
              "name":"Forge Onward",
              "cost":null,
              "type":{
                 "id":1,
                 "name":"spray"
              },
              "quality":{  
                 "name":"common"
              }
           }
        }